# Database connection - update username/password as needed
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/web_ban_linh_kien?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Bangkok}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:q1a2z3x4}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.ddl-auto=none

# JDBC pool settings (optional)
spring.datasource.initialization-mode=never

# Server port
server.port=8080

# Logging
logging.level.root=INFO

# File upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.jpa.show-sql=true

# Security Settings
#screct key de tao JWT+xac thuc
app.tokenSecret=
app.tokenExpirationMsec=3600000
 #dia chi backend redirect sau khi login Google ok.
app.authorizedRedirectUris=http://localhost:5173/oauth2/redirect

# Spring Security OAuth2
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/oauth2/callback/{registrationId}
spring.security.oauth2.client.registration.google.scope=email,profile

# Jackson Config for Hibernate Lazy Proxies
spring.jackson.serialization.fail-on-empty-beans=false

# VNPay Configuration
   # //terminal id
vnpay.tmnCode=
  #secrect key de tao chu ky securehash
vnpay.hashSecret=
  #url trang tt vnpay
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  #URL VNPay goi ve sau khi TT xong.
vnpay.returnUrl=http://localhost:8080/api/vnpay/payment-return


# Gemini api key cho chatbot
gemini.api.key=